<a href="https://colab.research.google.com/github/Marcolosan/Estructura-de-datos-con-Python/blob/main/Estructura_de_datos.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Vectores**

In [3]:
import numpy as np  # Importar la librería de numpy
# Vector
v = np.array([4, 5, 6])
print(v)
# Matriz
m = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(m)

print('Número de elementos en v ', v.size)
print('Número de elementos en m ', m.size)

[4 5 6]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Número de elementos en v  3
Número de elementos en m  9


***Ejercicios 1 - Listas*** 

Crea un array o arreglo unidimensional donde le indiques el tamaño por teclado y crear una función que rellene el array o arreglo con los múltiplos de un número pedido por teclado. Por ejemplo, si defino un array de tamaño 5 y elijo un 3 en la función, el array contendrá 3, 6, 9, 12, 15. Muestralos por pantalla usando otra función distinta.

In [14]:
n = int(input(u"Ingrese el tamaño del arreglo"))
m = int(input(u"Ingrese el número de múltiplos"))
A = []
for i in range (0,n):
    A.append(i*m)
print (A)

Ingrese el tamaño del arreglo10
Ingrese el número de múltiplos2
[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]
